name       : gmime
version    : 3.0.2
release    : 3
source     :
    - https://download.gnome.org/sources/gmime/3.0/gmime-3.0.2.tar.xz : 0deb460111ffa2ec672677da339b82dedeb28b258ccdb216daa21c81a9472fb2
homepage   : http://spruce.sourceforge.net/gmime/
license    : LGPL-2.1
component  : programming
summary    : MIME parsing/creation library
builddeps  :
    - vala
description: |
    GMime is a C/C++ library which may be used for the creation and parsing of messages using the Multipurpose Internet Mail Extension (MIME)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
