name       : gmime
version    : 3.0.5
release    : 5
source     :
    - https://download.gnome.org/sources/gmime/3.0/gmime-3.0.5.tar.xz : 2f5353ac1062aa58c4855cc7691a0778c84339c654301a6bc0e95ba8427b85e0
homepage   : http://spruce.sourceforge.net/gmime/
license    : LGPL-2.1
component  : programming
summary    : MIME parsing/creation library
builddeps  :
    - vala
description: |
    GMime is a C/C++ library which may be used for the creation and parsing of messages using the Multipurpose Internet Mail Extension (MIME)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
