name       : gmime
version    : 3.2.6
release    : 13
source     :
    - https://download.gnome.org/sources/gmime/3.2/gmime-3.2.6.tar.xz : abff194c7c4802fba2e233890d09dde8bf7170c3ad5e13000601c8d5b3c44717
license    : LGPL-2.1-only
component  : programming.library
summary    : MIME parsing/creation library
description: |
    GMime is a C/C++ library which may be used for the creation and parsing of messages using the Multipurpose Internet Mail Extension (MIME)
builddeps  :
    - gpgme-devel
    - libassuan-devel
    - vala
setup      : |
    %configure --enable-crypto --disable-static
build      : |
    %make
install    : |
    %make_install
