name       : gmime
version    : 3.2.7
release    : 15
source     :
    - https://download.gnome.org/sources/gmime/3.2/gmime-3.2.7.tar.xz : 2aea96647a468ba2160a64e17c6dc6afe674ed9ac86070624a3f584c10737d44
license    : LGPL-2.1-only
component  : programming.library
summary    : MIME parsing/creation library
description: |
    GMime is a C/C++ library which may be used for the creation and parsing of messages using the Multipurpose Internet Mail Extension (MIME)
builddeps  :
    - gpgme-devel
    - libassuan-devel
    - vala
setup      : |
    %configure --enable-crypto --disable-static
build      : |
    %make
install    : |
    %make_install
