name       : gmime
version    : 3.2.3
release    : 10
source     :
    - https://download.gnome.org/sources/gmime/3.2/gmime-3.2.3.tar.xz : 6a0875eeb552ab447dd54853a68ced62217d863631048737dd97eaa2713e7311
license    : LGPL-2.1-only
component  : programming.library
summary    : MIME parsing/creation library
description: |
    GMime is a C/C++ library which may be used for the creation and parsing of messages using the Multipurpose Internet Mail Extension (MIME)
builddeps  :
    - gpgme-devel
    - libassuan-devel
    - vala
setup      : |
    %configure --enable-crypto --disable-static
build      : |
    %make
install    : |
    %make_install
