name       : gmime
version    : 3.0.3
release    : 4
source     :
    - https://download.gnome.org/sources/gmime/3.0/gmime-3.0.3.tar.xz : 94d06a39ed18250fcfc71b6fcf4757038bf0d7fc79d16e4942c04a0fa79d96e3
homepage   : http://spruce.sourceforge.net/gmime/
license    : LGPL-2.1
component  : programming
summary    : MIME parsing/creation library
builddeps  :
    - vala
description: |
    GMime is a C/C++ library which may be used for the creation and parsing of messages using the Multipurpose Internet Mail Extension (MIME)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
