name       : gmime
version    : 2.6.23
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gmime/2.6/gmime-2.6.23.tar.xz : 7149686a71ca42a1390869b6074815106b061aaeaaa8f2ef8c12c191d9a79f6a
homepage   : http://spruce.sourceforge.net/gmime/
license    : LGPL-2.1
component  : programming
summary    : MIME parsing/creation library
builddeps  :
    - vala
description: |
    GMime is a C/C++ library which may be used for the creation and parsing of messages using the Multipurpose Internet Mail Extension (MIME)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
