name       : gmime
version    : 3.2.4
release    : 11
source     :
    - https://download.gnome.org/sources/gmime/3.2/gmime-3.2.4.tar.xz : 249ea7c0e080b067aa9669162c36b181b402f6cf6cebc4999d838c6f1e81d024
license    : LGPL-2.1-only
component  : programming.library
summary    : MIME parsing/creation library
description: |
    GMime is a C/C++ library which may be used for the creation and parsing of messages using the Multipurpose Internet Mail Extension (MIME)
builddeps  :
    - gpgme-devel
    - libassuan-devel
    - vala
setup      : |
    %configure --enable-crypto --disable-static
build      : |
    %make
install    : |
    %make_install
