name       : gmime
version    : 3.2.5
release    : 12
source     :
    - https://download.gnome.org/sources/gmime/3.2/gmime-3.2.5.tar.xz : fb7556501f85c3bf3e65fdd82697cbc4fa4b55dccd33ad14239ce0197e78ba59
license    : LGPL-2.1-only
component  : programming.library
summary    : MIME parsing/creation library
description: |
    GMime is a C/C++ library which may be used for the creation and parsing of messages using the Multipurpose Internet Mail Extension (MIME)
builddeps  :
    - gpgme-devel
    - libassuan-devel
    - vala
setup      : |
    %configure --enable-crypto --disable-static
build      : |
    %make
install    : |
    %make_install
